language: php
php:
  - 7.0
  
sudo: false
dist: trusty

before_script:
  - php bin/vendors.php install --reinstall
  - php app/console doctrine:database:create
  - php app/console bloginy:init -l
script: phpunit -c app/

services:
    - mysql
